cloud:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/halitkalayci/4.5-project # yeni repo
          default-label: master
          search-paths:
            - configurations/
            - configurations/{application}
server:
  port: 8989