cloud:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Cihan-KARA-hub/turkcell-library-microservice # yeni repo
          default-label: main
          search-paths:
            - configurations/
            - configurations/{application}
server:
  port: 8989