spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Cihan-KARA-hub/turkcell-library-microservice
          default-label: main
          search-paths:
            - configurations/
            - configurations/{application}

server:
  port: 8787